// SPDX-License-Identifier: Apache-2.0

export const SUPPORTED_SURFACES = [
  "getMe",
  "getChat",
  "sendMessage",
  "editMessageText",
  "deleteMessage",
  "deleteMessages",
  "forwardMessage",
  "copyMessage",
  "getUpdates",
  "setWebhook",
  "deleteWebhook",
  "getWebhookInfo",
  "editMessageReplyMarkup",
  "pinChatMessage",
  "unpinChatMessage",
  "unpinAllChatMessages",
  "answerCallbackQuery",
  "sendPoll",
  "stopPoll",
  "setMessageReaction",
  "sendPhoto",
  "sendDocument",
  "sendVideo",
  "sendAudio",
  "sendVoice",
  "sendMediaGroup",
  "editMessageCaption",
  "getFile",
  "sendChatAction",
  "getChatAdministrators",
  "getChatMemberCount",
  "getChatMember",
  "setChatTitle",
  "setChatDescription",
  "setChatPermissions",
  "banChatMember",
  "unbanChatMember",
  "restrictChatMember",
  "promoteChatMember",
  "leaveChat",
];

export const unsupportedEnvelope = {
  status: 501,
  body: {
    ok: false as const,
    error_code: 501,
    description: "Not Found",
    _twin: {
      fidelity: "unsupported" as const,
      supported_surfaces: SUPPORTED_SURFACES,
    },
  },
} as const;
