// SPDX-License-Identifier: Apache-2.0
// Export-surface guard, for the cloud control-plane half of the former
// `@pome-sh/shared-types` barrel (these clusters moved to `cli/src/contract/`; the trace.

import { describe, expect, it } from "vitest";
import * as api from "../../../src/contract/index.js";
// TYPE-surface guard: `Object.keys` only sees runtime values, so dropping an `export
// type` / `export interface` — or a whole type-only leaf re-export — would.
import type {
  AcceptInviteRequest,
  AcceptInviteResponse,
  AgentResponse,
  ApiError,
  ApiErrorType,
  ApiKey,
  ApiKeyCreated,
  CreateAgentRequest,
  CreateEvalSessionResponse,
  CreateInviteRequest,
  CreateInviteResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  CriterionDef,
  CriterionDefInput,
  FinalizeAcceptedResponse,
  FinalizeCompletedStatusResponse,
  FinalizeFailedStatusResponse,
  FinalizeFailureError,
  FinalizeInitialResponse,
  FinalizeQueuedStatusResponse,
  FinalizeRequest,
  FinalizeResponse,
  FinalizeRunningStatusResponse,
  FinalizeStatusResponse,
  FinalizeStatusUrl,
  GmailSeedState,
  GithubSeedState,
  Manifest,
  ManifestAgent,
  ManifestInput,
  MeResponse,
  PerTwinStateKeys,
  PersistedTask,
  PlanTier,
  SeedEnvelope,
  SeedState,
  Session,
  SessionPublic,
  SessionState,
  SlackSeedState,
  StateUploadUrlEntry,
  StateUploadUrlResponse,
  StripeSeedState,
  SubmitResultRequest,
  SubmitResultResponse,
  Task,
  TaskConfig,
  Team,
  TeamInvite,
  TeamMember,
  TeamRole,
  UsageResponse,
  User,
} from "../../../src/contract/index.js";

// Referencing every imported type keeps the guard alive under
// noUnusedLocals-style settings; the tuple is never instantiated.
type _TypeSurfaceAssert = [
  AcceptInviteRequest,
  AcceptInviteResponse,
  AgentResponse,
  ApiError,
  ApiErrorType,
  ApiKey,
  ApiKeyCreated,
  CreateAgentRequest,
  CreateEvalSessionResponse,
  CreateInviteRequest,
  CreateInviteResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  CriterionDef,
  CriterionDefInput,
  FinalizeAcceptedResponse,
  FinalizeCompletedStatusResponse,
  FinalizeFailedStatusResponse,
  FinalizeFailureError,
  FinalizeInitialResponse,
  FinalizeQueuedStatusResponse,
  FinalizeRequest,
  FinalizeResponse,
  FinalizeRunningStatusResponse,
  FinalizeStatusResponse,
  FinalizeStatusUrl,
  GmailSeedState,
  GithubSeedState,
  Manifest,
  ManifestAgent,
  ManifestInput,
  MeResponse,
  PerTwinStateKeys,
  PersistedTask,
  PlanTier,
  SeedEnvelope,
  SeedState,
  Session,
  SessionPublic,
  SessionState,
  SlackSeedState,
  StateUploadUrlEntry,
  StateUploadUrlResponse,
  StripeSeedState,
  SubmitResultRequest,
  SubmitResultResponse,
  Task,
  TaskConfig,
  Team,
  TeamInvite,
  TeamMember,
  TeamRole,
  UsageResponse,
  User,
];
// Compile-time anchor: exactly one tuple entry per guarded type. The literal
// type on the left fails to compile if an entry is added or removed above
// without updating the count.
const TYPE_SURFACE_SIZE: _TypeSurfaceAssert["length"] = 54;

// Runtime value exports (types are erased and cannot appear on `Object.keys`).
const EXPECTED_EXPORTS = [
  "CRITERION_KINDS",
  "LEGACY_CRITERION_KIND_MAP",
  "LEGACY_TASK_VOCAB_KEY_MAP",
  "MOUNTED_TWINS",
  "SLUG_MAX_LENGTH",
  "SLUG_RE",
  // snake_case aliases accepted in a task `## Config` block (F-1681).
  "TASK_CONFIG_SNAKE_CASE_KEY_MAP",
  "acceptInviteRequestSchema",
  "acceptInviteResponseSchema",
  "agentResponseSchema",
  "agentSlugSchema",
  "apiErrorSchema",
  "apiErrorTypeSchema",
  "apiKeyCreatedSchema",
  "apiKeySchema",
  "buildManifestJsonSchema",
  "correlatorKindSchema",
  "createAgentRequestSchema",
  "createEvalSessionResponseSchema",
  "createInviteRequestSchema",
  "createInviteResponseSchema",
  "createSessionRequestSchema",
  "createSessionResponseSchema",
  "criterionDefSchema",
  "criterionKindSchema",
  "criterionResultSchema",
  "criterionSchema",
  "deriveAgentSlug",
  "deterministicCriterionResultSchema",
  "finalizeAcceptedResponseSchema",
  "finalizeCompletedStatusResponseSchema",
  "finalizeFailedStatusResponseSchema",
  "finalizeFailureErrorSchema",
  "finalizeInitialResponseSchema",
  "finalizeQueuedStatusResponseSchema",
  "finalizeRequestSchema",
  "finalizeResponseSchema",
  "finalizeRunningStatusResponseSchema",
  "finalizeStatusResponseSchema",
  "finalizeStatusUrlSchema",
  "githubSeedStateSchema",
  "gmailSeedStateSchema",
  "isMultiTwinSeedEnvelope",
  "judgeModelSchema",
  "laneSchema",
  "linearSeedStateSchema",
  "manifestAgentSchema",
  "manifestSchema",
  "meResponseSchema",
  "normalizeTaskConfigKeys",
  "normalizeTaskVocabKeys",
  "perTwinStateKeysSchema",
  "persistedTaskSchema",
  "planTierSchema",
  "probabilisticCriterionResultSchema",
  "providerScopedSeedStateSchema",
  "runSchema",
  "seedEnvelopeSchema",
  "seedStateSchema",
  "sessionPublicSchema",
  "sessionSchema",
  "sessionStateSchema",
  "slackSeedStateSchema",
  "stateUploadUrlEntrySchema",
  "stateUploadUrlResponseSchema",
  "stepSchema",
  "stripeSeedStateSchema",
  "submitResultRequestSchema",
  "submitResultResponseSchema",
  // A task's population (`conformance` / `restraint` / `adversarial`).
  "taskClassSchema",
  "taskConfigSchema",
  "taskSchema",
  "teamInviteSchema",
  "teamMemberSchema",
  "teamRoleSchema",
  "teamSchema",
  "usageResponseSchema",
  "userSchema",
] as const;

describe("cli/src/contract barrel export surface", () => {
  it("re-exports exactly the pre-refactor runtime value surface", () => {
    expect(Object.keys(api).sort()).toEqual([...EXPECTED_EXPORTS]);
  });

  it("guards the TYPE surface (54 types/interfaces)", () => {
    // The real guard is the type-only import + _TypeSurfaceAssert tuple above,
    // enforced at typecheck time. This assertion just anchors the count at
    // runtime so the guard's scope is visible in test output.
    expect(TYPE_SURFACE_SIZE).toBe(54);
  });
});
