#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Case table for emit-example-catalog. Every case asserts the RED direction: a
// generator that has quietly stopped refusing a bad tree emits a catalog that
// looks exactly like a good one, and the first anyone hears of it is a 404 at
// scaffold time on a user's machine.

import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildCatalog, renderCatalog } from "./emit-example-catalog.mjs";

let failures = 0;
function fail(name, detail) {
  failures += 1;
  console.error(`✗ ${name}\n  ${detail}`);
}
function pass(name) {
  console.log(`✓ ${name}`);
}

function check(name, predicate, detail) {
  if (predicate) pass(name);
  else fail(name, detail);
}

function threw(fn) {
  try {
    fn();
    return null;
  } catch (err) {
    return err.message;
  }
}

/** A repo root holding `{ "<root>/<name>": { description, homepage, files } }`. */
function fixture(spec) {
  const root = mkdtempSync(join(tmpdir(), "example-catalog-"));
  const tracked = new Map();
  for (const [rel, { description, homepage, files }] of Object.entries(spec)) {
    mkdirSync(join(root, rel), { recursive: true });
    const manifest = { name: `@pome-sh/${rel.split("/").at(-1)}-example` };
    if (description !== undefined) manifest.description = description;
    if (homepage !== undefined) manifest.homepage = homepage;
    writeFileSync(join(root, rel, "package.json"), JSON.stringify(manifest));
    tracked.set(rel, files.map((file) => `${rel}/${file}`));
  }
  return { root, listTrackedFiles: (_repoRoot, rel) => tracked.get(rel) ?? [] };
}

const OK_FILES = ["package.json", "src/index.ts"];

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/merge-agent": { description: "A merge agent. Teaches merges.", files: OK_FILES },
    "integration-examples/braintrust": { description: "Braintrust harness.", files: OK_FILES },
  });
  const entries = buildCatalog(root, listTrackedFiles);
  check(
    "1. one entry per example, across BOTH roots, in EXAMPLE_ROOTS order",
    entries.length === 2 &&
      entries[0].id === "merge-agent" &&
      entries[0].root === "agent-examples" &&
      entries[1].id === "braintrust" &&
      entries[1].root === "integration-examples",
    JSON.stringify(entries.map((e) => e.rel)),
  );
  check(
    "2. the file list is repo-relative paths made example-relative",
    JSON.stringify(entries[0].files) === JSON.stringify(["package.json", "src/index.ts"]),
    JSON.stringify(entries[0].files),
  );
  check(
    "3. the description is the example's own package.json description",
    entries[0].description === "A merge agent. Teaches merges.",
    entries[0].description,
  );
}

{
  const { root, listTrackedFiles } = fixture({});
  check(
    "4. an empty scan is RED, not an empty catalog",
    /refusing to emit an empty catalog/.test(threw(() => buildCatalog(root, listTrackedFiles)) ?? ""),
    "buildCatalog returned instead of throwing on a tree with no examples",
  );
}

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/braintrust": { description: "The examinee.", files: OK_FILES },
    "integration-examples/braintrust": { description: "The harness.", files: OK_FILES },
  });
  check(
    "5. one id claimed by two roots is RED — `--example` takes one id",
    /claimed by both/.test(threw(() => buildCatalog(root, listTrackedFiles)) ?? ""),
    "buildCatalog silently kept one of two examples sharing an id",
  );
}

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/merge-agent": { description: undefined, files: OK_FILES },
  });
  check(
    "6. an example with no package.json description is RED",
    /has no `description`/.test(threw(() => buildCatalog(root, listTrackedFiles)) ?? ""),
    "buildCatalog emitted an id a reader cannot choose between",
  );
}

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/merge-agent": { description: "A merge agent.", files: [] },
  });
  check(
    "7. an example git tracks no files under is RED, not an id that scaffolds nothing",
    /tracks no files under/.test(threw(() => buildCatalog(root, listTrackedFiles)) ?? ""),
    "buildCatalog emitted an id whose scaffold would be an empty directory",
  );
}

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/merge-agent": {
      description: "A merge agent.",
      files: ["package.json", "src/index.ts", "README.md"],
    },
  });
  const rendered = renderCatalog(buildCatalog(root, listTrackedFiles));
  check(
    "8. the rendered module says it is generated and names the command that regenerates it",
    rendered.includes("GENERATED by scripts/emit-example-catalog.mjs") &&
      rendered.includes("npm run emit:example-catalog"),
    rendered.slice(0, 200),
  );
  check(
    "9. files render sorted, so a readdir order change is not a diff",
    rendered.indexOf('"README.md"') < rendered.indexOf('"package.json"'),
    rendered,
  );
}

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/walked": {
      description: "Walked in the docs.",
      homepage: "https://docs.pome.sh/quickstart/coding-agent",
      files: OK_FILES,
    },
    "integration-examples/plain": { description: "No docs walk.", files: OK_FILES },
  });
  const entries = buildCatalog(root, listTrackedFiles);
  const rendered = renderCatalog(entries);
  check(
    "13. a package.json homepage reaches the catalog; its absence emits no field",
    entries[0].homepage === "https://docs.pome.sh/quickstart/coding-agent" &&
      entries[1].homepage === undefined &&
      rendered.includes('homepage: "https://docs.pome.sh/quickstart/coding-agent",') &&
      !rendered.includes("homepage: undefined"),
    JSON.stringify(entries.map((e) => e.homepage)),
  );
}

{
  const { root, listTrackedFiles } = fixture({
    "agent-examples/walked": {
      description: "Walked in the docs.",
      homepage: "/quickstart/coding-agent",
      files: OK_FILES,
    },
  });
  check(
    "14. a homepage that is not an absolute https URL is RED — it prints as a next step",
    /not an absolute https URL/.test(threw(() => buildCatalog(root, listTrackedFiles)) ?? ""),
    "buildCatalog emitted a homepage nobody can follow from a terminal",
  );
}

{
  // The real tree, not a fixture: the properties above are only worth anything
  // if the repo they gate actually satisfies them.
  const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const entries = buildCatalog(repoRoot);
  const ids = entries.map((e) => e.id);
  check(
    `10. the real tree yields ${entries.length} example(s), every id unique`,
    entries.length >= 2 && new Set(ids).size === ids.length,
    JSON.stringify(ids),
  );
  check(
    "11. every real entry carries at least a package.json",
    entries.every((e) => e.files.includes("package.json")),
    JSON.stringify(entries.filter((e) => !e.files.includes("package.json")).map((e) => e.rel)),
  );
  check(
    "12. both roots are represented — a one-root catalog is the #499 failure mode",
    new Set(entries.map((e) => e.root)).size === 2,
    JSON.stringify([...new Set(entries.map((e) => e.root))]),
  );
}

if (failures > 0) {
  console.error(`\n${failures} case(s) failed.`);
  process.exit(1);
}
console.log("\nAll cases passed.");
